In [1]:
# EXERCISE 1
import numpy as np
arr=np.arange(1,11)
arr=arr.reshape(2,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# EXERCISE 2
import numpy as np
arr=np.arange(1,21)
arr=arr[5:15]
print(arr)

[ 6  7  8  9 10 11 12 13 14 15]


In [21]:
# EXERCISE 3
import pandas as pd
series=pd.Series({'apple':3,'bananas':2,'orange':1})
series['pears']=4
print(series)

apple      3
bananas    2
orange     1
pears      4
dtype: int64


In [15]:
# EXERCISE 4
import pandas as pd 
import numpy as np
data={
    'Name':['Snith','Ashwini','Najeeb','Deleena','Jeevan','Arunima','Rishi','Abijith','Sharon','Ajith'],
    'Age':np.arange(25,35),
    'Gender':['male','female','male','female','male','female','male','male','male','male']
}
df=pd.DataFrame(data)
print(df)

      Name  Age  Gender
0    Snith   25    male
1  Ashwini   26  female
2   Najeeb   27    male
3  Deleena   28  female
4   Jeevan   29    male
5  Arunima   30  female
6    Rishi   31    male
7  Abijith   32    male
8   Sharon   33    male
9    Ajith   34    male


In [17]:
# EXERCISE 5
df['Occupation']=['Programmer','Manager','Analyst','Programmer','Manager','Analyst','Programmer','Manager','Analyst','Programmer']
print(df)

      Name  Age  Gender  Occupation
0    Snith   25    male  Programmer
1  Ashwini   26  female     Manager
2   Najeeb   27    male     Analyst
3  Deleena   28  female  Programmer
4   Jeevan   29    male     Manager
5  Arunima   30  female     Analyst
6    Rishi   31    male  Programmer
7  Abijith   32    male     Manager
8   Sharon   33    male     Analyst
9    Ajith   34    male  Programmer


In [37]:
# EXERCISE 6
selected_df = df[df['Age'] >= 30]
print(selected_df)

      Name  Age  Gender  Occupation
5  Arunima   30  female     Analyst
6    Rishi   31    male  Programmer
7  Abijith   32    male     Manager
8   Sharon   33    male     Analyst
9    Ajith   34    male  Programmer


In [41]:
# EXERCISE 7
df.to_csv('data.csv' , index=False)
df_read=pd.read_csv('data.csv')
print(df_read)

      Name  Age  Gender  Occupation
0    Snith   25    male  Programmer
1  Ashwini   26  female     Manager
2   Najeeb   27    male     Analyst
3  Deleena   28  female  Programmer
4   Jeevan   29    male     Manager
5  Arunima   30  female     Analyst
6    Rishi   31    male  Programmer
7  Abijith   32    male     Manager
8   Sharon   33    male     Analyst
9    Ajith   34    male  Programmer
